### ISSUE TITLE
docs: add contributing guidelines and issue forms

### ISSUE THREAD

**Issue by Anmol-Baranwal** [JuanPabloDiaz/freeForGeeks#11]
Hi @JuanPabloDiaz,

Here are some suggestions to boost the project:

- Implement issue forms (link, category, broken links, feedback) in .yml format.
- Include a contributing.md file so that people can understand how to contribute to devKit.
- You can also make a web-app and add sorting feature where developers can filter resources based on their needs.

> Having contributing guidelines is essential if you want others to contribute to the repository.

**Comment by JuanPabloDiaz** [comment]
thank you for your suggestions. I will be working on this.
